### ISSUE TITLE
An error when I run SWAV:

### ISSUE THREAD

**Issue by gosling123456** [PaddlePaddle/PASSL#187]

**Comment by gosling123456** [comment]
when I use CPU in Aistudio to train this net, there is an error occupied :
Traceback (most recent call last):
  File "tools/train.py", line 57, in <module>
    main(args, cfg)
  File "tools/train.py", line 50, in main
    trainer.train()
  File "/home/aistudio/work/PASSL/passl/engine/trainer.py", line 330, in train
    mixup_fn=self.mixup_fn)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PASSL/passl/modeling/architectures/swav.py", line 67, in forward
    return self.train_iter(*inputs, **kwargs)
  File "/home/aistudio/work/PASSL/passl/modeling/architectures/swav.py", line 58, in train_iter
    _out = self.backbone(paddle.concat(inputs[start_idx: end_idx]))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PASSL/passl/modeling/backbones/resnetswav.py", line 118, in forward
    x = self.bn1(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py", line 1096, in forward
    sync_batch_norm_out, _, _, _, _, _ = _C_ops.sync_batch_norm(
AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'sync_batch_norm'
How can I solve this problem?

**Comment by jerrywgz** [comment]
You need GPU version of PaddlePaddle for SWAV
