### ISSUE TITLE
KeyError: 'Global'

### ISSUE THREAD

**Issue by famersalltheday** [PaddlePaddle/PASSL#191]
Traceback (most recent call last):
  File "tools/train.py", line 39, in <module>
    main()
  File "tools/train.py", line 34, in main
    engine = Engine(config, mode="train")
  File "D:\PASSL-main\tools\passl\engine\engine.py", line 51, in __init__
    self.task_type = self.config["Global"].get("task_type",
KeyError: 'Global'

请问我在参考官方说明运行的时候出现这个bug，配置文件中并没有Global。 我运行环境是win10

**Comment by famersalltheday** [comment]
我运行tools_v110版本：
Traceback (most recent call last):
  File "tools_v110/train.py", line 57, in <module>
    main(args, cfg)
  File "tools_v110/train.py", line 33, in main
    trainer = Trainer(cfg)
  File "D:\PASSL-main\tools_v110\passl\engine\trainer.py", line 147, in __init__
    cfg.dataloader.train, self.device)
  File "D:\tools_v110\passl\datasets\builder.py", line 84, in build_dataloader
    loader_cfg = cfg_.pop('loader')
KeyError: 'loader'
